---
- stat: path="{{prefix}}/vim-{{vim.version}}"
  register: stat_vim

- name: make
  when: not stat_vim.stat.exists
  include: _make.yml
  vars:
    vim_src_url: "https://github.com/vim/vim/archive/v{{vim.version}}.tar.gz"
    vim_src_fpath: "{{work_dir}}/vim-{{vim.version}}.tar.gz"
    vim_unarchived: "{{work_dir}}/vim-{{vim.version}}"
    vim_prefix: "{{prefix}}/vim-{{vim.version}}"

# vim:st=2 sts=2 sw=2:
