---
- stat: path="{{ vim_prefix }}/bin/vim"
  register: stat_vim_bin
  tags:
    - vim

- name: install build depends
  tags:
    - vim
  sudo: yes
  dnf: name={{item}} state=present
  with_items:
    - git
    - gcc
    - make
    - autoconf
    - ncurses-devel
    - perl-devel
    - perl-ExtUtils-Embed
    - ruby-devel
    - python-devel
    - python3-devel
    - lua-devel
    - luajit-devel
    - gtk2-devel
    - libXt-devel
  when: not stat_vim_bin.stat.exists

- name: clear work dir
  tags:
    - vim
  sudo: yes
  file: >-
    path="{{vim_build_dir}}"
    state=absent
  when: not stat_vim_bin.stat.exists

- name: create work dir
  tags:
    - vim
  sudo: yes
  file: >-
    path="{{vim_build_dir}}"
    state=directory mode=0777
  when: not stat_vim_bin.stat.exists

- name: clone src
  tags:
    - vim
  git: >-
    repo=https://github.com/vim/vim.git
    dest="{{vim_build_dir}}"
    version="{{vim.ver}}"
    force=yes
  when: not stat_vim_bin.stat.exists

- name: make autoconf
  tags:
    - vim
  command: >-
    make autoconf
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

- name: configure
  tags:
    - vim
  command: >-
    ./configure
    --prefix="{{vim_prefix}}"
    --with-features=huge
    --without-x
    --disable-gui
    --enable-multibyte
    --enable-perlinterp=dynamic
    --enable-pythoninterp=dynamic
    --enable-rubyinterp=dynamic
    --enable-luainterp=dynamic
    --with-lua-prefix=/usr
    --with-luajit
    --enable-gpm
    --enable-cscope
    --enable-fontset
    --enable-fail-if-missing
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

- name: make
  tags:
    - vim
  command: >-
    make
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

- name: mkdir install path
  tags:
    - vim
  sudo: yes
  file: >-
    path="{{vim_prefix}}"
    state=directory
  when: not stat_vim_bin.stat.exists

- name: make install
  tags:
    - vim
  sudo: yes
  command: >-
    make install
    chdir="{{vim_build_dir}}/src"
  when: not stat_vim_bin.stat.exists

- name: create bundle dir
  tags:
    - vim
  file: >-
    path="~/.vim/bundle"
    state=directory

- name: clone neobundle.vim
  tags:
    - vim
  git: >-
    repo=https://github.com/Shougo/neobundle.vim.git
    dest="~/.vim/bundle/neobundle.vim"
    force=yes

- name: clone vimproc.vim
  tags:
    - vim
  git: >-
    repo=https://github.com/Shougo/vimproc.vim.git
    dest="~/.vim/bundle/vimproc.vim"
    force=yes

- stat: path="~/.vim/bundle/vimproc.vim/autoload/vimproc_linux64.so"
  register: stat_vimproc_linux64_so
  tags:
    - vim

- name: make vimproc.vim
  tags:
    - vim
  command: >-
    make clean
    chdir="~/.vim/bundle/vimproc.vim"

- name: make vimproc.vim
  tags:
    - vim
  command: >-
    make
    chdir="~/.vim/bundle/vimproc.vim"

- name: init bundles
  tags:
    - vim
  command: >-
    {{ vim_prefix }}/bin/vim
    -N -U NONE -i NONE -V1 -e -s
    --cmd "set encoding=utf-8"
    --cmd "set termencoding=utf-8"
    --cmd "source ~/.vimrc"
    --cmd "NeoBundleInstall!"
    --cmd "qall!"
  ignore_errors: yes

- name: add path
  tags:
    - vim
  shell: >-
    sed -i -e
    's!^#export PATH="$VIM:$PATH"$!export PATH="{{vim_prefix}}/bin:$PATH"!'
    ~/.bash.include

- name: update path
  tags:
    - vim
  shell: >-
    sed -i -e
    's!^export PATH="/opt/vim/.\+/bin:$PATH"$!export PATH="{{vim_prefix}}/bin:$PATH"!'
    ~/.bash.include

# vim:st=2 sts=2 sw=2:
