---
- name: get_os
  shell: cat /etc/redhat-release
  register: setup_redhat_release

- name: get tz
  shell: timedatectl | grep 'Time zone'
  register: setup_tz

- name: change tz to JST
  become: yes
  when:
    - "'stdout' in setup_tz"
    - "'Asia/Tokyo' not in setup_tz.stdout"
  command: timedatectl set-timezone Asia/Tokyo

- name: install epel-release
  when:
    - "'stdout' in setup_redhat_release"
    - "'CentOS' in setup_redhat_release.stdout"
  become: yes
  package:
    name: epel-release
    state: present

- name: install the 'Development tools' package group
  become: yes
  package:
    name: "@Development tools"
    state: present

- name: install tmux
  become: yes
  package:
    name: tmux
    state: latest

- name: install msmtp
  become: yes
  package:
    name: msmtp
    state: latest

- name: create work dir
  become: yes
  file: path="{{work_dir}}" state=directory

- name: create .ssh dir
  file:
    path: "~/.ssh"
    state: directory

- stat: path="~/.ssh/id_rsa.pem"
  register: stat_ssh_id_rsa_pem

- name: create .ssh/id_rsa
  command: ssh-keygen -t rsa -b 4096 -P "" -C "{{hostname}} {{email}}" -f ~/.ssh/id_rsa.pem
  args:
    chdir: "~/.ssh"

- name: mv pub file
  command: mv id_rsa.pem.pub id_rsa.pub
  args:
    chdir: "~/.ssh"

- name: create flag file
  become: yes
  file:
    path: "{{setup.flag_fpaht}}"
    state: touch

# vim:st=2 sts=2 sw=2:
