---
- name: upgrade all packages
  sudo: yes
  dnf: name=* state=latest

- name: get tz
  shell: timedatectl | grep 'Time zone'
  register: tz

- name: change tz to JST
  sudo: yes
  command: timedatectl set-timezone Asia/Tokyo
  when: tz.stdout.find('Asia/Tokyo') == -1

- name: install the 'Development tools' package group
  sudo: yes
  dnf: name="@Development tools" state=present

- name: install tmux
  sudo: yes
  dnf: name=tmux state=latest

- name: install msmtp
  sudo: yes
  dnf: name=msmtp state=latest

- name: create work dir
  sudo: yes
  file: path="{{work_dir}}" state=directory

- name: create misc dir
  file: path="~/misc" state=directory

- name: create .ssh dir
  file: >-
    path="~/.ssh"
    state=directory

- stat: path="~/.ssh/id_rsa"
  register: stat_ssh_id_rsa

- name: create .ssh/id_rsa
  command: >-
    ssh-keygen -t rsa -b 4096 -P "" -C "{{hostname}} {{email}}" -f ~/.ssh/id_rsa
    chdir="~/.ssh"
  when: not stat_ssh_id_rsa.stat.exists

- stat: path="~/misc/dotfiles"
  register: stat_dotfiles

- name: clone dotfiles
  git: repo=https://github.com/jptomo/dotfiles.git dest="~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

- name: remove origin
  command: git remote rm origin
  args:
    chdir: "~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

- name: add origin
  command: git remote add origin git@github.com:jptomo/dotfiles.git
  args:
    chdir: "~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

- name: init rcs
  command: sh setup.sh
  args:
    chdir: "~/misc/dotfiles"
  when: not stat_dotfiles.stat.exists

# vim:st=2 sts=2 sw=2:
