---
- stat: path="{{setup.flag_fpaht}}"
  register: stat_setup

- name: (RedHat cor) upgrade all packages
  when: ansible_os_family == "RedHat"
  become: yes
  package:
    name: "*"
    state: latest

#- name: (Debian cor) upgrade all packages
#  when: ansible_os_family == "Debian"
#  become: yes
#  apt:
#    name: "*"
#    state: latest

- name: setup
  when: not stat_setup.stat.exists
  include: _setup.yml

# vim:st=2 sts=2 sw=2:
