---
- stat: path="{{setup_flag_fpaht}}"
  register: stat_setup

- name: upgrade all packages
  become: yes
  dnf: name=* state=latest

- name: get tz
  shell: timedatectl | grep 'Time zone'
  when: not stat_setup.stat.exists
  register: tz

- name: change tz to JST
  become: yes
  when: "not stat_setup.stat.exists and 'stdout' in tz and tz.stdout.find('Asia/Tokyo') == -1"
  command: timedatectl set-timezone Asia/Tokyo

- name: install the 'Development tools' package group
  become: yes
  when: not stat_setup.stat.exists
  dnf: name="@Development tools" state=present

- name: install tmux
  become: yes
  when: not stat_setup.stat.exists
  dnf: name=tmux state=latest

- name: install msmtp
  become: yes
  when: not stat_setup.stat.exists
  dnf: name=msmtp state=latest

- name: create work dir
  become: yes
  when: not stat_setup.stat.exists
  file: path="{{work_dir}}" state=directory

- name: create .ssh dir
  when: not stat_setup.stat.exists
  file:
    path: "~/.ssh"
    state: directory

- stat: path="~/.ssh/id_rsa.pem"
  register: stat_ssh_id_rsa_pem
  when: not stat_setup.stat.exists

- name: create .ssh/id_rsa
  when: not stat_setup.stat.exists and not stat_ssh_id_rsa_pem.stat.exists
  command: ssh-keygen -t rsa -b 4096 -P "" -C "{{hostname}} {{email}}" -f ~/.ssh/id_rsa.pem
  args:
    chdir: "~/.ssh"

- name: create flag file
  become: yes
  when: not stat_setup.stat.exists
  file:
    path: "{{setup_flag_fpaht}}"
    state: touch

# vim:st=2 sts=2 sw=2:
