---
- stat: path="{{setup.flag_fpaht}}"
  register: stat_setup

- name: (RedHat cor) upgrade all packages
  when: ansible_os_family == "RedHat"
  become: yes
  package:
    name: "*"
    state: latest

#- name: (Debian cor) upgrade all packages
#  when: ansible_os_family == "Debian"
#  become: yes
#  apt:
#    name: "*"
#    state: latest

- import_tasks: _setup.yml
  when: not stat_setup.stat.exists

# vim:ft=yaml sts=2 sw=2:
