---
- stat: path="{{setup_flag_fpaht}}"
  register: stat_setup

- name: upgrade all packages
  become: yes
  dnf: name=* state=latest

- name: setup
  when: not stat_setup.stat.exists
  include: _setup.yml

# vim:st=2 sts=2 sw=2:
