---
- name: "{{python_target}} : (RedHat) install build depends"
  when: ansible_os_family == "RedHat"
  become: yes
  package:
    name:
      - zlib-devel
      - bzip2-devel
      - openssl-devel
      - ncurses-devel
      - sqlite-devel
      - readline-devel
      - gdbm-devel
      - libdb-devel
      - xz-devel
      - tk-devel
      - tcl-devel
      - expat-devel
    state: present

- name: "{{python_target}} : (Debian) install build depends"
  when: ansible_os_family == "Debian"
  become: yes
  package:
    name:
      - libssl-dev
      - zlib1g-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libgdbm-dev
      - libdb5.3-dev
      - libbz2-dev
      - libexpat1-dev
      - liblzma-dev
      - tk-dev
    state: present

- name: "{{python_target}} : create work dir"
  become: yes
  file:
    path: "{{python_work_dir}}"
    state: directory
    mode: '0755'

- name: "{{python_target}} : clear old src dir"
  become: yes
  file:
    path: "{{python_src_dir}}"
    state: absent

- name: "{{python_target}} : fetch src archive and unarchive"
  become: yes
  unarchive:
    src: "{{python_src_url}}"
    dest: "{{python_work_dir}}"
    remote_src: yes

- name: "{{python_target}} : configure"
  become: yes
  command: "{{python_configure}}"
  args:
    chdir: "{{python_src_dir}}"

- name: "{{python_target}} : make"
  become: yes
  command: make
  args:
    chdir: "{{python_src_dir}}"

- name: "{{python_target}} : make install"
  become: yes
  command: make install
  args:
    chdir: "{{python_src_dir}}"

# vim:ft=yaml sts=2 sw=2:
