---
- stat: path="/opt/own/Python-{{python.py27_version}}"
  register: stat_python27
  tags:
    - never
    - python27

- stat: path="/opt/own/Python-{{python.py27_version}}-shared"
  register: stat_python27_shared
  tags:
    - never
    - python27-shared

- stat: path="/opt/own/Python-{{python.py36_version}}"
  register: stat_python36
  tags:
    - never
    - python36

- stat: path="/opt/own/Python-{{python.py36_version}}-shared"
  register: stat_python36_shared
  tags:
    - never
    - python36-shared

- stat: path="/opt/own/Python-{{python.py37_version}}"
  register: stat_python37
  tags:
    - never
    - python37

- stat: path="/opt/own/Python-{{python.py37_version}}-shared"
  register: stat_python37_shared
  tags:
    - never
    - python37-shared

- stat: path="/opt/own/Python-{{python.py38_version}}"
  register: stat_python38
  tags:
    - never
    - python38

- stat: path="/opt/own/Python-{{python.py38_version}}-shared"
  register: stat_python38_shared
  tags:
    - never
    - python38-shared

- stat: path="/opt/own/Python-{{python.py39_version}}"
  register: stat_python39
  tags:
    - never
    - python39

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py27_version}}"
    python_src_url: "https://www.python.org/ftp/python/{{python.py27_version}}/Python-{{python.py27_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py27_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py27_version}}"
    python_src_dir: "{{work_dir}}/Python-{{python.py27_version}}/Python-{{python.py27_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py27_version}}"
      --enable-unicode=ucs4
  tags:
    - never
    - python27
  when: not stat_python27.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py27_version}}-shared"
    python_src_url: "https://www.python.org/ftp/python/{{python.py27_version}}/Python-{{python.py27_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py27_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py27_version}}-shared"
    python_src_dir: "{{work_dir}}/Python-{{python.py27_version}}-shared/Python-{{python.py27_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py27_version}}-shared"
      --enable-unicode=ucs4
      --enable-shared
  tags:
    - never
    - python27-shared
  when: not stat_python27_shared.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py36_version}}"
    python_src_url: "https://www.python.org/ftp/python/{{python.py36_version}}/Python-{{python.py36_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py36_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py36_version}}"
    python_src_dir: "{{work_dir}}/Python-{{python.py36_version}}/Python-{{python.py36_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py36_version}}"
  tags:
    - never
    - python36
  when: not stat_python36.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py36_version}}-shared"
    python_src_url: "https://www.python.org/ftp/python/{{python.py36_version}}/Python-{{python.py36_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py36_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py36_version}}-shared"
    python_src_dir: "{{work_dir}}/Python-{{python.py36_version}}-shared/Python-{{python.py36_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py36_version}}-shared"
      --enable-shared
  tags:
    - never
    - python36-shared
  when: not stat_python36_shared.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py37_version}}"
    python_src_url: "https://www.python.org/ftp/python/{{python.py37_version}}/Python-{{python.py37_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py37_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py37_version}}"
    python_src_dir: "{{work_dir}}/Python-{{python.py37_version}}/Python-{{python.py37_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py37_version}}"
  tags:
    - never
    - python37
  when: not stat_python37.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py37_version}}-shared"
    python_src_url: "https://www.python.org/ftp/python/{{python.py37_version}}/Python-{{python.py37_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py37_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py37_version}}-shared"
    python_src_dir: "{{work_dir}}/Python-{{python.py37_version}}-shared/Python-{{python.py37_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py37_version}}-shared"
      --enable-shared
  tags:
    - never
    - python37-shared
  when: not stat_python37_shared.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py38_version}}"
    python_src_url: "https://www.python.org/ftp/python/{{python.py38_version}}/Python-{{python.py38_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py38_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py38_version}}"
    python_src_dir: "{{work_dir}}/Python-{{python.py38_version}}/Python-{{python.py38_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py38_version}}"
  tags:
    - never
    - python38
  when: not stat_python38.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py38_version}}-shared"
    python_src_url: "https://www.python.org/ftp/python/{{python.py38_version}}/Python-{{python.py38_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py38_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py38_version}}-shared"
    python_src_dir: "{{work_dir}}/Python-{{python.py38_version}}-shared/Python-{{python.py38_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py38_version}}-shared"
      --enable-shared
  tags:
    - never
    - python38-shared
  when: not stat_python38_shared.stat.exists

- import_tasks: _cmmi.yml
  vars:
    python_target: "{{python.py39_version}}"
    python_src_url: "https://www.python.org/ftp/python/{{python.py39_version}}/Python-{{python.py39_version}}.tgz"
    python_src: "{{work_dir}}/Python-{{python.py39_version}}.tgz"
    python_work_dir: "{{work_dir}}/Python-{{python.py39_version}}"
    python_src_dir: "{{work_dir}}/Python-{{python.py39_version}}/Python-{{python.py39_version}}"
    python_configure: >-
      ./configure
      --prefix="{{prefix}}/Python-{{python.py39_version}}"
  tags:
    - never
    - python39
  when: not stat_python39.stat.exists

# vim:ft=yaml sts=2 sw=2:
