---
- stat: path="{{prefix}}/git-{{git.version}}"
  register: stat_git

- import_tasks: _make.yml
  vars:
    git_src_url: "https://github.com/git/git/archive/v{{git.version}}.tar.gz"
    git_src_fpath: "{{work_dir}}/git-{{git.version}}.tar.gz"
    git_unarchived: "{{work_dir}}/git-{{git.version}}"
    git_prefix: "{{prefix}}/git-{{git.version}}"
  when: not stat_git.stat.exists

# vim:ft=yaml sts=2 sw=2:
