---
# configure, make, make install

- stat: path="{{ python_prefix }}/bin/python{{python_bin_ver}}"
  register: stat_python_bin

- name: install the 'Development tools' package group
  sudo: yes
  dnf: name="@Development tools" state=present
  when: not stat_python_bin.stat.exists

- name: install build depends
  sudo: yes
  dnf: name={{item}} state=present
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - gdbm-devel
    - db4-devel
    - libpcap-devel
    - xz-devel
    - tk-devel
    - tcl-devel
    - expat-devel
  when: not stat_python_bin.stat.exists

- name: clear old src dir
  sudo: yes
  file: >-
    path="{{python_src_dir}}"
    state=absent
  when: not stat_python_bin.stat.exists

- name: create work dir
  sudo: yes
  file: >-
    path="{{work_dir}}/python"
    state=directory mode=0777
  when: not stat_python_bin.stat.exists

- name: download src
  get_url: >-
    url="{{python_src_url}}"
    dest="{{python_src}}"
  when: not stat_python_bin.stat.exists

- name: unarchive
  unarchive: >-
    src="{{python_src}}"
    dest="{{work_dir}}/python"
  when: not stat_python_bin.stat.exists

- name: configure
  command: "{{python_configure}} chdir={{python_src_dir}}"
  when: not stat_python_bin.stat.exists

- name: make
  command: >-
    make
    chdir="{{python_src_dir}}"
  when: not stat_python_bin.stat.exists

- name: mkdir install path
  sudo: yes
  file: >-
    path="{{python_prefix}}"
    state=directory
  when: not stat_python_bin.stat.exists

- name: make install
  sudo: yes
  command: >-
    make install
    chdir="{{python_src_dir}}"
  when: not stat_python_bin.stat.exists

# vim:st=2 sts=2 sw=2:
