---
- name: cp repo file
  become: yes
  copy: >-
    src=fc22-home-ocaml.repo
    dest=/etc/yum.repos.d/home:ocaml.repo

- name: install opam
  become: yes
  dnf: name=opam state=latest

- name: install patch
  become: yes
  dnf: name=patch state=latest

- name: init opam
  command: opam init --comp={{ocaml_ver}}

- name: install ocaml
  command: opam switch {{ocaml_ver}}

- name: add opam config env
  shell: >-
    sed -i -e
    's/^#eval `opam config env`$/eval `opam config env`/'
    ~/.bash.include

# vim:st=2 sts=2 sw=2:
