---
- hosts: all
  gather_facts: True
  vars:
    hostname: "vm"
    email: "quickness.net@gmail.com"
    prefix: "/opt/own"
    work_dir: "/opt/own/work"
    setup:
      flag_fpaht: "/opt/own/work/.setup_flag_file"
    git:
      version: "2.18.0"
    vim:
      version: "8.1.0341"
    python:
      py2_version: "2.7.15"
      py3_version: "3.6.5"
    ocaml:
      version: "4.02.3"
    terraform:
      version: "0.11.7"
  roles:
    - role: 'setup'
      tags: ['setup', 'always']
    - role: 'git'
      tags: 'git'
    - role: 'vim'
      tags: 'vim'
    - role: 'python'
      tags: 'python2'
    - role: 'python'
      tags: 'python3'
    - role: 'terraform'
      tags: 'terraform'
    - role: 'ocaml'
      tags: 'ocaml'

# vim:ft=yaml st=2 sts=2 sw=2:
